### ISSUE TITLE
Estratègia

### ISSUE THREAD

**Issue by kenan-rhoton** [pernilsalat/one-bot-to-rule-them-all#7]
Estaria molt bé fer un document Estrategia.md on estigués explicada la estratègia que seguim i la que volem seguir.

A grosso modo imagino que la estratègia ideal deu ser alguna cosa com:

1. Recaptar la informació de l'estat actual
2. Aplicar una estratègia "tonta" als nostres bots i als de l'oponent
3. Evolucionar:
   1. intentar trobar el nostre millor moviment
   2. intentar trobar la millor resposta de l'oponent
   3. repetir ara amb més profunditat (torns + 1)
   4. Si en algún moment ens estem quedant sense temps, acceptar la nostra millor solució

**Comment by Masclins** [comment]
Ben vist. Avui ho creo
